---
language: python
python: "2.7"
env:
  - SITE=test.yml
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl
install:
  - pip install ansible==1.5.0
script:
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo"
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo | grep -q 'changed=0.*failed=0' && exit 0 || exit 1"
  - "curl http://localhost/"
